# Generated by Django 2.1 on 2018-08-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del evento', max_length=1000, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('CF', 'Conferencia'), ('SE', 'Seminario'), ('CG', 'Congreso'), ('CU', 'Curso')], help_text='Categoría del evento', max_length=20, verbose_name='Categoría')),
                ('lugar', models.CharField(help_text='Lugar donde se realizará el evento', max_length=1000, verbose_name='Lugar')),
                ('direccion', models.CharField(help_text='Dirección donde se realizará el evento', max_length=1000, verbose_name='Dirección')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio del evento', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de finalización del evento', verbose_name='Fecha de finalización')),
                ('tipo', models.CharField(choices=[('PR', 'Presencial'), ('VI', 'Virtual')], help_text='Tipo del evento: Presencial o virtual', max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
