# Generated by Django 2.1 on 2018-08-16 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_evento_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 8, 15, 21, 24, 18, 549038), help_text='Fecha y hora de creación del evento', verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
    ]
